#define IDD_MAIN          30
#define IDM_FILE          100
#define IDM_ABOUT         101
#define IDM_PU            102
#define IDM_PLAY          103
#define IDM_DELETE        104
#define IDM_ABORT         105
#define IDM_RELEASE       106
#define IDM_RECORD        107
#define IDM_PLAYFILE      108
#define IDM_STOP          109
#define IDD_ABOUT         200
#define IDC_STATE                   3
#define IDC_DCERESPONSE             5
#define IDC_SAVE                    6
#define IDC_PLAY                    7
#define IDC_CALLLIST                8
#define IDC_DELETE                  9
#define IDC_VERSION                 11
#define IDM_SETTINGS                102
#define IDD_SETTINGS                300
#define IDC_BAUD                    302
#define IDC_COM                     304
#define IDC_RINGS                   307
#define IDC_DCEVER                  201
#define IDC_ABORT                   31
#define IDC_RELEASE                 308
#define IDC_TITLES                  301
#define IDI_MSG                     400
