APIRET16 APIENTRY16 RPORT(USHORT uPort);
APIRET16 APIENTRY16 RPORTN(USHORT uPort, void * pDest, USHORT uCount);
void APIENTRY16 WPORT(USHORT uPort, USHORT);
APIRET16 APIENTRY16 RPORT16(USHORT uPort);
APIRET16 APIENTRY16 RPORTN16(USHORT uPort, void * pDest, USHORT uCount);
void APIENTRY16 WPORT16(USHORT uPort, USHORT);
APIRET16 APIENTRY16 Dos16PortAccess(USHORT uPort, USHORT, USHORT, USHORT);
// Include "SEGMENTS IO_TEXT IOPL" in your DEF file and export the functions
